/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkivebeenpwned;

import java.io.IOException;
import java.net.Proxy;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author GLLGRL68H26H282H
 */
public class MainForm_new extends javax.swing.JFrame {

    CheckPwnedWorker checkPwnedWorker;
    Proxy proxy;

    /**
     * Creates new form MainForm
     */
    public MainForm_new() {
        initComponents();
        btnStopSearch.setEnabled(false);
        
        startNetworking();
    }

    private void startNetworking(){
        NetworkProxy np = new NetworkProxy();
        np.init();
        proxy = np.getNetworkProxy();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAccounts = new javax.swing.JTextArea();
        btnCheckPwned = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblMaxAccountNumber = new javax.swing.JLabel();
        lblDi = new javax.swing.JLabel();
        lblCounterAccountNumber = new javax.swing.JLabel();
        lblCheckingAccount = new javax.swing.JLabel();
        btnStopSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAccounts.setColumns(20);
        txtAccounts.setRows(5);
        jScrollPane1.setViewportView(txtAccounts);

        btnCheckPwned.setText("Check Pwned");
        btnCheckPwned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckPwnedActionPerformed(evt);
            }
        });

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane2.setViewportView(txtResult);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Incolla l'elenco degli account da controllare su haveibeenpwned.com");

        lblMaxAccountNumber.setText("-");

        lblDi.setText("di");

        lblCounterAccountNumber.setText("-");

        lblCheckingAccount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCheckingAccount.setText(" ");
        lblCheckingAccount.setAlignmentX(1.0F);
        lblCheckingAccount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnStopSearch.setText("Stop");
        btnStopSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckPwned)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStopSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCheckingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCounterAccountNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaxAccountNumber))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckPwned)
                    .addComponent(lblMaxAccountNumber)
                    .addComponent(lblDi)
                    .addComponent(lblCounterAccountNumber)
                    .addComponent(lblCheckingAccount)
                    .addComponent(btnStopSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckPwnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckPwnedActionPerformed
        txtResult.setText("");
        String accounts = txtAccounts.getText().trim();
               
        if ("".equals(accounts)){
            return;
        }
        String[] temp = accounts.split("\n");
        ArrayList<String> testingAccounts = new ArrayList<String>(Arrays.asList(temp));
        
        btnCheckPwned.setEnabled(false);
        btnStopSearch.setEnabled(true);
        
      //  if (checkPwnedWorker == null) {
      if (checkPwnedWorker!=null){
          checkPwnedWorker.cancel(true);
      }
            checkPwnedWorker = new CheckPwnedWorker(testingAccounts, proxy) {
                @Override
                protected void done() {
                    super.done(); //To change body of generated methods, choose Tools | Templates.
                    try {
                        List<String> result = get();
                        txtResult.setText("");
                        for (String s : result) {
                            txtResult.append(s + "\n");
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainForm_new.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ExecutionException ex) {
                        Logger.getLogger(MainForm_new.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    btnCheckPwned.setEnabled(true);
                    btnStopSearch.setEnabled(false);
                    lblCheckingAccount.setText("");
                    lblCounterAccountNumber.setText("-");                    
                    lblMaxAccountNumber.setText("-");
                }

                private int counterAccountDone=0;
                @Override
                protected void process(List<PwnedResult> chunks) {                    
                    lblCounterAccountNumber.setText(String.valueOf(++counterAccountDone));
                    txtResult.append(chunks.get(0).ACCOUNT+"\n");
                    for (PwnedResult PR : chunks) {
                        lblCheckingAccount.setText(PR.ACCOUNT);
                        txtResult.append(PR.SERVER_REULT+"\n");
                    }
                }
            };
    //    }
    
        lblMaxAccountNumber.setText(String.valueOf(testingAccounts.size()));
        checkPwnedWorker.execute();

        //checkPwnedWorker.checkAccounts(testingAccounts);

    }//GEN-LAST:event_btnCheckPwnedActionPerformed

    private void btnStopSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopSearchActionPerformed
        
        checkPwnedWorker.stopSearch();
        btnCheckPwned.setEnabled(true);
        btnStopSearch.setEnabled(false);
    }//GEN-LAST:event_btnStopSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm_new().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckPwned;
    private javax.swing.JButton btnStopSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCheckingAccount;
    private javax.swing.JLabel lblCounterAccountNumber;
    private javax.swing.JLabel lblDi;
    private javax.swing.JLabel lblMaxAccountNumber;
    private javax.swing.JTextArea txtAccounts;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void DoAction(String testo) {
//        txtResult.append(testo + "\n");
//    }
}
